{
  "tasks": [
    {
      "id": "gimutsgl",
      "date": "2026-03-29",
      "done": false,
      "note": "",
      "time": "09:00",
      "techId": "9mt6dztf",
      "customerId": "m66zisfw",
      "serviceType": "mt"
    },
    {
      "id": "fy3wgrgw",
      "date": "2026-03-29",
      "done": false,
      "note": "",
      "time": "00:00",
      "techId": "n1zposo1",
      "customerId": "qqvovjem",
      "serviceType": "mt"
    },
    {
      "id": "6eznt4j9",
      "date": "2026-03-29",
      "done": false,
      "note": "",
      "time": "09:00",
      "techId": "9mt6dztf",
      "customerId": "jm0n28pr",
      "serviceType": "mt"
    },
    {
      "id": "8b2bnerp",
      "date": "2026-03-30",
      "done": false,
      "note": "",
      "time": "09:00",
      "techId": "9mt6dztf",
      "customerId": "m66zisfw",
      "serviceType": "ur"
    },
    {
      "id": "24nsi6s3",
      "date": "2026-03-29",
      "done": false,
      "note": "",
      "time": "09:00",
      "techId": "n1zposo1",
      "customerId": "jm0n28pr",
      "serviceType": "ur"
    }
  ],
  "appName": "AOT排班系統",
  "reports": {},
  "adminPin": "0000",
  "customers": [
    {
      "id": "m66zisfw",
      "fax": "",
      "code": "008",
      "name": "莫生",
      "note": "",
      "email": "lanwendy@netvigator.com",
      "tanks": 1,
      "address": "House A, 85-87 Ma Ling Path, Kau To Shan, Shatin, N.T.",
      "contact": "Wendy Lan",
      "sitePhone": "",
      "siteContact": "",
      "contactPhone": "23632826"
    },
    {
      "id": "xi9n6gzm",
      "fax": "26140946",
      "code": "028",
      "name": "施他彿",
      "note": "",
      "email": "Maggiema@pihlgp.com",
      "tanks": 1,
      "address": "",
      "contact": "Maggie Ma",
      "sitePhone": "",
      "siteContact": "",
      "contactPhone": "24243326"
    },
    {
      "id": "0fa67zzr",
      "fax": "",
      "code": "029",
      "name": "粉嶺牽陳太",
      "note": "",
      "email": "",
      "tanks": 1,
      "address": "粉嶺牽晴間2座31D",
      "contact": "陳太",
      "sitePhone": "",
      "siteContact": "",
      "contactPhone": "96226063"
    },
    {
      "id": "z6r3nzbv",
      "fax": "",
      "code": "058",
      "name": "ROYAL KING INTERNATIONAL LIMITED (繆氏)",
      "note": "",
      "email": "cheng@eikowada.com.hk",
      "tanks": 1,
      "address": "1/F, Sun Kwong Industrial Bldg, 1059-1061, Tung Chau West St, Lai Chi Kok, Kowoon",
      "contact": "Mr. Cheng",
      "sitePhone": "",
      "siteContact": "",
      "contactPhone": "27420431"
    },
    {
      "id": "08uvye6a",
      "fax": "25763385",
      "code": "066",
      "name": "優雅閣業主立案法團",
      "note": "",
      "email": "",
      "tanks": 1,
      "address": "大坑道 60 號優雅閣",
      "contact": "Suki",
      "sitePhone": "",
      "siteContact": "",
      "contactPhone": "25777430"
    },
    {
      "id": "3piajip6",
      "fax": "",
      "code": "088",
      "name": "屯門建榮",
      "note": "",
      "email": "candy@laicheung.com.hk\nsummertsang@laicheung.com.hk",
      "tanks": 1,
      "address": "屯門建榮街 33 號建榮工業大廈 9 樓 1 室",
      "contact": "曾小姐",
      "sitePhone": "",
      "siteContact": "",
      "contactPhone": "59785368"
    },
    {
      "id": "dz1vvx5e",
      "fax": "27353922",
      "code": "098",
      "name": "JP Workshop Interiors Ltd (金𩣑花園)",
      "note": "",
      "email": "",
      "tanks": 1,
      "address": "Unit A-B, 23/F, YHC Tower, No.1 Shueng Yuet Road, Kowloon Bay, Kowloon, Hong Kong",
      "contact": "Pan Ng",
      "sitePhone": "",
      "siteContact": "",
      "contactPhone": "27353928/ 93591349"
    },
    {
      "id": "jm0n28pr",
      "fax": "",
      "code": "252",
      "name": "九龍塘基督教中心幼稚園",
      "note": "",
      "email": "",
      "tanks": 1,
      "address": "九龍塘窩打老道103號地下",
      "contact": "鄧老師",
      "sitePhone": "",
      "siteContact": "",
      "contactPhone": "67570237"
    },
    {
      "id": "d9gsw4nf",
      "fax": "",
      "code": "263",
      "name": "263",
      "note": "",
      "email": "",
      "tanks": 1,
      "address": "21科進路逸瓏灣2期 T9 6樓 E室",
      "contact": "許先生",
      "sitePhone": "",
      "siteContact": "",
      "contactPhone": "93380860"
    },
    {
      "id": "942ciyqz",
      "fax": "",
      "code": "280",
      "name": "China Overseas Holdings Limited",
      "note": "",
      "email": "go-billing@cohl.com",
      "tanks": 1,
      "address": "10/F., Pacific Place, 1 Queen’s Road East",
      "contact": "Rosanna Yuen",
      "sitePhone": "",
      "siteContact": "",
      "contactPhone": "2723 7385"
    },
    {
      "id": "evdvvqis",
      "fax": "",
      "code": "286",
      "name": "Guna technologies ltd",
      "note": "",
      "email": "",
      "tanks": 1,
      "address": "新蒲崗大有街31號善美工業大廈1303室",
      "contact": "Alex Chung",
      "sitePhone": "",
      "siteContact": "",
      "contactPhone": "93193269"
    },
    {
      "id": "35shxy3h",
      "fax": "",
      "code": "289",
      "name": "289",
      "note": "",
      "email": "",
      "tanks": 1,
      "address": "擎天半島1座76樓D室",
      "contact": "郝先生",
      "sitePhone": "",
      "siteContact": "",
      "contactPhone": "5313 5896"
    },
    {
      "id": "1war3xol",
      "fax": "",
      "code": "293",
      "name": "豐泰米行(香港)有限公司",
      "note": "",
      "email": "",
      "tanks": 1,
      "address": "青衣長好街8號時力工業大廈1樓B室",
      "contact": "黃小姐",
      "sitePhone": "",
      "siteContact": "",
      "contactPhone": "24356680"
    },
    {
      "id": "a4pts67v",
      "fax": "",
      "code": "295",
      "name": "健采集團有限公司",
      "note": "",
      "email": "",
      "tanks": 1,
      "address": "火炭黃竹洋街富昌中心6樓B&C室",
      "contact": "黃小姐/ 梁小姐",
      "sitePhone": "",
      "siteContact": "",
      "contactPhone": "98764808/ 60930213"
    },
    {
      "id": "22w11fvz",
      "fax": "",
      "code": "297",
      "name": "297",
      "note": "",
      "email": "",
      "tanks": 1,
      "address": "薄扶林摩星嶺道 61 號福利別墅第四座",
      "contact": "陳太",
      "sitePhone": "",
      "siteContact": "",
      "contactPhone": "5562 3228"
    },
    {
      "id": "qqvovjem",
      "fax": "",
      "code": "298",
      "name": "Toyzeroplus Ltd",
      "note": "",
      "email": "",
      "tanks": 1,
      "address": "",
      "contact": "Ms May Chan",
      "sitePhone": "",
      "siteContact": "",
      "contactPhone": "35802770"
    },
    {
      "id": "cu2jdxh6",
      "fax": "",
      "code": "299",
      "name": "悠閑木匠",
      "note": "",
      "email": "",
      "tanks": 1,
      "address": "元朗蝶翠峰13座10C室",
      "contact": "Anita Chung",
      "sitePhone": "",
      "siteContact": "",
      "contactPhone": "9287 9488"
    },
    {
      "id": "0e4sj1fm",
      "fax": "",
      "code": "301",
      "name": "301",
      "note": "",
      "email": "",
      "tanks": 1,
      "address": "淺水灣道129號4座11樓",
      "contact": "Zhong xiao rui",
      "sitePhone": "",
      "siteContact": "",
      "contactPhone": "5525 2382"
    },
    {
      "id": "d40n04r3",
      "fax": "",
      "code": "308",
      "name": "308",
      "note": "",
      "email": "",
      "tanks": 1,
      "address": "House 12, Rosecliff, 20 Tai Tam Road, HK",
      "contact": "Mary Chan",
      "sitePhone": "",
      "siteContact": "",
      "contactPhone": "6712 0082"
    },
    {
      "id": "8ui312b5",
      "fax": "",
      "code": "312",
      "name": "Delta Pyramax Company Limited",
      "note": "",
      "email": "",
      "tanks": 1,
      "address": "九龍灣宏光道39號宏天廣場28樓",
      "contact": "Ms. Regina Wong",
      "sitePhone": "",
      "siteContact": "",
      "contactPhone": "25112118"
    },
    {
      "id": "u71oyyx5",
      "fax": "",
      "code": "319",
      "name": "319",
      "note": "",
      "email": "",
      "tanks": 1,
      "address": "葵涌和宜合道恆利中心 11 樓",
      "contact": "麥先生",
      "sitePhone": "",
      "siteContact": "",
      "contactPhone": "9611 5418"
    },
    {
      "id": "rh9e2bwq",
      "fax": "",
      "code": "325",
      "name": "Trend Up Investment (HK) Limited",
      "note": "",
      "email": "",
      "tanks": 1,
      "address": "Room 2306-2313, 23/F, The Center, 99 Queen's Road Central, Central",
      "contact": "Stephen Tong",
      "sitePhone": "",
      "siteContact": "",
      "contactPhone": "‪5188 1428‬"
    },
    {
      "id": "11s4lxvb",
      "fax": "",
      "code": "335",
      "name": "都會駅",
      "note": "",
      "email": "",
      "tanks": 1,
      "address": "將軍澳調景嶺都會駅1座59樓H室",
      "contact": "Joyce Hung",
      "sitePhone": "",
      "siteContact": "",
      "contactPhone": "6339 9419"
    },
    {
      "id": "tlxu011o",
      "fax": "",
      "code": "336",
      "name": "竹林明堂護理安老院",
      "note": "",
      "email": "",
      "tanks": 1,
      "address": "5 ShaWan Drive, Pok Fu Lam, H.K.",
      "contact": "Caden Lo",
      "sitePhone": "",
      "siteContact": "",
      "contactPhone": "2817 2281"
    },
    {
      "id": "g7wv2dha",
      "fax": "",
      "code": "339",
      "name": "Reitar Logtech Group Limited",
      "note": "",
      "email": "admin@reitar.io",
      "tanks": 1,
      "address": "",
      "contact": "Ms. Leung",
      "sitePhone": "",
      "siteContact": "",
      "contactPhone": "34613652"
    }
  ],
  "recurring": [],
  "adminLabel": "Celine",
  "technicians": [
    {
      "id": "9mt6dztf",
      "pin": "0000",
      "name": "Sam",
      "canEdit": true,
      "canView": [
        "9mt6dztf"
      ]
    },
    {
      "id": "n1zposo1",
      "pin": "1111",
      "name": "阿肥",
      "canEdit": true,
      "canView": [
        "n1zposo1"
      ]
    }
  ],
  "serviceTypes": [
    {
      "bg": "#eff6ff",
      "id": "mt",
      "color": "#2563eb",
      "label": "定期保養"
    },
    {
      "bg": "#fdf4ff",
      "id": "cl",
      "color": "#a21caf",
      "label": "清洗服務"
    },
    {
      "bg": "#ecfeff",
      "id": "eg",
      "color": "#0e7490",
      "label": "工程施作"
    },
    {
      "bg": "#fef2f2",
      "id": "ur",
      "color": "#dc2626",
      "label": "臨時急件"
    }
  ]
}